name: Build

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build-unix:
    runs-on: [ubuntu-latest, macos-latest]

    strategy:
      matrix:
        cxx: [g++-11, clang++-13, clang++-14]
        build_type: [Debug, Release]

        include:
          - cxx: g++-11
            install: sudo apt-get install -y g++-11
          - cxx: clang++-13
            install: sudo apt-get install -y clang++-13
          - cxx: clang++-14
            install: sudo apt-get install -y clang++-14

    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        run: ${{matrix.install}}

      - name: Make build directory
        run: mkdir ${{github.workspace}}/build

      - name: Configure cmake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=${{matrix.cxx}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build