name: Test Sandbox

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cxx: [g++, clang++]
        build_type: [Debug, Release]

        include:
          - os: ubuntu-latest
            install: sudo apt-get install ninja-build xorg-dev
          - os: macos-latest
            install: brew install ninja

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        shell: bash
        run: ${{matrix.install}}

      - name: Build
        shell: bash
        run: ./build_unix.sh ${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.cxx}}

      - name: Run Sandbox
        run: ./liger-sandbox